name: Deploy Staging 🚀

on:
  push:
    branches: [ "main" ]

jobs:
  deploy-staging:
    name: Deploy to staging server
    runs-on: ubuntu-latest

    env:
      APP_STG_PATH: ${{ vars.APP_STG_PATH }}
      GIT_URL: ${{ vars.GIT_URL }}
      APP_STG_PORT: ${{ secrets.APP_STG_PORT }}
      MINIO_STG_ENDPOINT: ${{ secrets.MINIO_STG_ENDPOINT }}
      MINIO_STG_ACCESS_KEY: ${{ secrets.MINIO_STG_ACCESS_KEY }}
      MINIO_STG_SECRET_KEY: ${{ secrets.MINIO_STG_SECRET_KEY }}

    steps:
      - name: Execute deployment command
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST_STAGING }}
          username: ${{ secrets.SSH_USER_NAME_STAGING }}
          key: ${{ secrets.SSH_PRIVATE_KEY_STAGING }}
          envs: APP_STG_PORT, APP_STG_PATH, MINIO_STG_ENDPOINT, MINIO_STG_ACCESS_KEY, MINIO_STG_SECRET_KEY, GIT_URL
          script: |
            if [[ -d "${APP_STG_PATH}" ]]; then 
              cd "${APP_STG_PATH}"
              sudo docker compose down 
              git pull origin main
            else
              mkdir -p "${APP_STG_PATH}"
              ssh-keyscan github.com > ~/.ssh/known_hosts
              git clone "${GIT_URL}" "${APP_STG_PATH}"
              cd "${APP_STG_PATH}"
            fi

            # Check if .env file exists or create it
            if [[ ! -f .env ]]; then
              touch .env
            fi

            # If there are any envars update
            echo "APP_STG_PORT=${APP_STG_PORT}" >> .env
            echo "MINIO_STG_ENDPOINT=${MINIO_STG_ENDPOINT}" >> .env
            echo "MINIO_STG_ACCESS_KEY=${MINIO_STG_ACCESS_KEY}" >> .env
            echo "MINIO_STG_SECRET_KEY=${MINIO_STG_SECRET_KEY}" >> .env

            # Run app
            sudo docker compose up app-staging --build --detach
      
      - name: Hit Endpoint
        run: |
          sleep 20
          curl ${{ vars.STAGING_URL }}
